### ISSUE TITLE
for function task:estimateInputStat(  ). do we need batchSize?

### ISSUE THREAD

**Issue by comc35** [cvpa3/dl-practice#7]
Good evening, I have short question in preprocessing part.
In function task:estimateInputStat(  ), there is default(?) variable
               local batchSize = self.opt.batchSize
and in the function explanation it says I can use self:getBatchTrain(),
        -- You can use self:getBatchTrain().
but I wonder what is batchSize for, and how can we use function getBatchTrain(), as getBatchTrain() finally need estimated RGB mean, which is because it must call self:processImageTrain()

**Comment by zzangjinsun** [comment]
I am in the same problem.

Based on the comments in source codes, dependencies are
estimateInputStat -> getBatchTrain -> processImageTrain -> normalizeImage -> inputStat
and I got an error because I don't have inputStat values for the beginning.

I think it would be better to use loadImage() directly in the estimateInputStat()...

**Comment by cvpa3** [comment]
getBatchTrain should make your code short. 
Why dont you try "if rgbMean exists, blahblah; else, blahblah; end"?

TA.
